In [1]:
import pandas as pd 
import numpy as np
import random

In [2]:
df = pd.read_csv("./Data/credit_customers.csv")
df.head()

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6.0,critical/other existing credit,radio/tv,1169.0,no known savings,>=7,4.0,male single,none,...,real estate,67.0,none,own,2.0,skilled,1.0,yes,yes,good
1,0<=X<200,48.0,existing paid,radio/tv,5951.0,<100,1<=X<4,2.0,female div/dep/mar,none,...,real estate,22.0,none,own,1.0,skilled,1.0,none,yes,bad
2,no checking,12.0,critical/other existing credit,education,2096.0,<100,4<=X<7,2.0,male single,none,...,real estate,49.0,none,own,1.0,unskilled resident,2.0,none,yes,good
3,<0,42.0,existing paid,furniture/equipment,7882.0,<100,4<=X<7,2.0,male single,guarantor,...,life insurance,45.0,none,for free,1.0,skilled,2.0,none,yes,good
4,<0,24.0,delayed previously,new car,4870.0,<100,1<=X<4,3.0,male single,none,...,no known property,53.0,none,for free,2.0,skilled,2.0,none,yes,bad

In [3]:
dfDatosParaComprobar= pd.DataFrame(columns=df.columns)

In [4]:
random.seed(922)
random = random.sample(range(0,999),100)
random

[51,
 518,
 949,
 836,
 945,
 899,
 502,
 982,
 200,
 918,
 211,
 755,
 70,
 717,
 246,
 302,
 321,
 118,
 594,
 129,
 952,
 288,
 327,
 225,
 965,
 875,
 758,
 326,
 443,
 900,
 882,
 150,
 447,
 234,
 742,
 645,
 969,
 152,
 705,
 750,
 775,
 266,
 917,
 569,
 776,
 155,
 204,
 416,
 207,
 334,
 642,
 365,
 825,
 625,
 55,
 702,
 419,
 592,
 289,
 130,
 473,
 378,
 994,
 628,
 126,
 167,
 669,
 438,
 149,
 838,
 545,
 53,
 672,
 243,
 656,
 2,
 964,
 13,
 816,
 548,
 690,
 262,
 815,
 968,
 454,
 442,
 627,
 953,
 841,
 76,
 859,
 943,
 220,
 420,
 760,
 912,
 977,
 581,
 493,
 86]

In [6]:
for i in random:
    if(random.count(i)>1):
        print("Se repite",i)
print("No se repite ningun numero")

No se repite ningun numero

In [7]:
for i in range (100):
    dfDatosParaComprobar.loc[i]=df.loc[random[i]]
    df.drop(index=random[i], inplace=True)
df.reset_index(drop=True)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6.0,critical/other existing credit,radio/tv,1169.0,no known savings,>=7,4.0,male single,none,...,real estate,67.0,none,own,2.0,skilled,1.0,yes,yes,good
1,0<=X<200,48.0,existing paid,radio/tv,5951.0,<100,1<=X<4,2.0,female div/dep/mar,none,...,real estate,22.0,none,own,1.0,skilled,1.0,none,yes,bad
2,<0,42.0,existing paid,furniture/equipment,7882.0,<100,4<=X<7,2.0,male single,guarantor,...,life insurance,45.0,none,for free,1.0,skilled,2.0,none,yes,good
3,<0,24.0,delayed previously,new car,4870.0,<100,1<=X<4,3.0,male single,none,...,no known property,53.0,none,for free,2.0,skilled,2.0,none,yes,bad
4,no checking,36.0,existing paid,education,9055.0,no known savings,1<=X<4,2.0,male single,none,...,no known property,35.0,none,for free,1.0,unskilled resident,2.0,yes,yes,good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,no checking,12.0,existing paid,furniture/equipment,1736.0,<100,4<=X<7,3.0,female div/dep/mar,none,...,real estate,31.0,none,own,1.0,unskilled resident,1.0,none,yes,good
896,<0,30.0,existing paid,used car,3857.0,<100,1<=X<4,4.0,male div/sep,none,...,life insurance,40.0,none,own,1.0,high qualif/self emp/mgmt,1.0,yes,yes,good
897,no checking,12.0,existing paid,radio/tv,804.0,<100,>=7,4.0,male single,none,...,car,38.0,none,own,1.0,skilled,1.0,none,yes,good
898,<0,45.0,existing paid,radio/tv,1845.0,<100,1<=X<4,4.0,male single,none,...,no known property,23.0,none,for free,1.0,skilled,1.0,yes,yes,bad
899,0<=X<200,45.0,critical/other existing credit,used car,4576.0,100<=X<500,unemployed,3.0,male single,none,...,car,27.0,none,own,1.0,skilled,1.0,none,yes,good

In [8]:
dfDatosParaComprobar

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,0<=X<200,27.0,delayed previously,used car,5965.0,<100,>=7,1.0,male single,none,...,car,30.0,none,own,2.0,high qualif/self emp/mgmt,1.0,yes,yes,good
1,<0,6.0,existing paid,new car,1203.0,100<=X<500,>=7,3.0,male single,none,...,life insurance,43.0,none,own,1.0,skilled,1.0,yes,yes,good
2,no checking,24.0,existing paid,radio/tv,3621.0,100<=X<500,>=7,2.0,male single,none,...,car,31.0,none,own,2.0,skilled,1.0,none,yes,bad
3,no checking,12.0,existing paid,radio/tv,886.0,no known savings,1<=X<4,4.0,female div/dep/mar,none,...,car,21.0,none,own,1.0,skilled,1.0,none,yes,good
4,0<=X<200,48.0,no credits/all paid,new car,8358.0,500<=X<1000,<1,1.0,female div/dep/mar,none,...,car,30.0,none,own,2.0,skilled,1.0,none,yes,good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0<=X<200,30.0,existing paid,radio/tv,2991.0,no known savings,>=7,2.0,female div/dep/mar,none,...,car,25.0,none,own,1.0,skilled,1.0,none,yes,good
96,0<=X<200,18.0,delayed previously,business,2427.0,no known savings,>=7,4.0,male single,none,...,life insurance,42.0,none,own,2.0,skilled,1.0,none,yes,good
97,0<=X<200,12.0,critical/other existing credit,new car,3124.0,<100,<1,1.0,male single,none,...,real estate,49.0,bank,own,2.0,unskilled resident,2.0,none,yes,good
98,0<=X<200,6.0,existing paid,radio/tv,368.0,no known savings,>=7,4.0,male single,none,...,life insurance,38.0,none,own,1.0,skilled,1.0,none,yes,good
99,0<=X<200,18.0,critical/other existing credit,furniture/equipment,1295.0,<100,<1,4.0,female div/dep/mar,none,...,life insurance,27.0,none,own,2.0,skilled,1.0,none,yes,good

In [9]:
dfDatosParaComprobar.to_csv("./Data/datosParaComprobarModelo.csv")

In [10]:
df.to_csv("./Data/datosParaHacerEntrenarModelo.csv")